### PR TITLE
Remove duplicated Maintainer line

### PR DESCRIPTION
**Pull request by tomsquest**

### CODE REVIEW

**Comment by CedricGatay** [comment]
Thank you, I didn't know where my head was when I did this :)

**Comment by tomsquest** [comment]
Bipolar ? :roll_eyes:

**Comment by CedricGatay** [comment]
Damned, I think you’re right !

__
Cedric Gatay (@Cedric_Gatay)
code-troopers.com | www.bloggure.info | cedric.gatay.fr | hopwork

**Comment by tomsquest** [comment]
(your other self will certainly reopen this issue...)

**Pull request merged**
